version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: akshitpareek/mean-backend
    container_name: mean-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/yourdbname
    depends_on:
      - mongo

  frontend:
    image: akshitpareek/mean-frontend
    container_name: mean-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mongo-data:
